### ISSUE TITLE
bug: 회원가입 시 유저이름과 비밀번호 불일치 문제  

### ISSUE THREAD

**Issue by ksh9409255** [Lotte-SweetPotatos/WARr-Cinema#17]
### 설명
![](https://velog.velcdn.com/images/ksh9409255/post/eb02f8b7-a96a-4032-a1d0-cf17ecb89835/image.PNG)
위와 같이 유저이름이 비밀번호에 매칭이 되고 비밀번호에 유저이름이 매칭이 되는 문제

**Comment by soulgchoi** [comment]
form 화면에서 값을 잘못 줘서 생긴 문제 같습니다. 해당 부분 고쳐서 스타일과 함께 반영하겠습니다~!
