### ISSUE TITLE
argument: controller 구현에 대한 논의

### ISSUE THREAD

**Issue by ksh9409255** [Lotte-SweetPotatos/WARr-Cinema#7]
### 설명
movie controller의 경우 영화 메인, 영화 상세, 영화 예매를 하나의 controller에서 구현하는지 각각의 controller를 구현하는지 논의가 필요
### 진행상황
- [x] controller 논의

**Comment by soulgchoi** [comment]
제안: 셋이서 각각의 Controller를 만들어 작업한다. 이후 모두 머지한 뒤 별도의 리팩토링을 거쳐서 하나로 통합한다.
- 충돌 시 해결하는 시간을 줄일 수 있다.
- 리팩토링 시간이 따로 필요
- 하나에 합쳐서 작업할 경우 당장의 프로젝트 수행은 빠르지만 이후 충돌 해결하는 과정이 길어질 수 있다.

**Comment by soulgchoi** [comment]
결론: 학습 차원에서 한 Controller에서 작업한 뒤 conflict 해결을 경험한다.
