### ISSUE TITLE
Argument: dao의 구현메서드에 관하여

### ISSUE THREAD

**Issue by ksh9409255** [Lotte-SweetPotatos/WARr-Cinema#8]
### 설명
dao를 구현할 경우 필요한 기능만을 구현하는 것인지, crud와 같은 기본 기능들을 모두 구현해야 하는지에 관한 논의가 필요합니다.
### 진행상황
- [x] dao 기능 구현

**Comment by soulgchoi** [comment]
결론: 필요한 기능만 구현한다.

**Comment by ksh9409255** [comment]
추가적인 기능은 고도화 영역이다.
또한 팀원들간의 혼동이 올 수 있으니 필요한 기능만 구현하는 것으로 한다.

**Comment by namhyeop** [comment]
필요한 기능만 있는게 맞는거 같습니다. 사용하지 않는 코드 때문에 가독성에 문제가 생길 수 있을거 같아요.
